api_login_check:
  path: /api/login_check

#NelmioApiDocBundle:
#  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
#  prefix:   /api/doc

app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

#index:
#    path: /
#    controller: App\Controller\DefaultController::index
